language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 0.7
    - nightly
matrix:
  allow_failures:
    - julia: nightly
    
notifications:
  email: false

after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
