name = "ExpmV"
uuid = "e7fedf88-7a0b-11e8-3562-f39b41888c88"
authors = ["Matteo Rossi <teo.red90@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
